# ////////////////////////////////////////
# FISH-CAM  Configuration commune
# ////////////////////////////////////////
spring.application.name=FishCam
spring.config.import=optional:file:.env

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA commun
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Serveur
server.port=8080
# Format dates (Cameroun)
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=Africa/Douala

# Upload fichiers (avatars, futurs PDF)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

# Resoud le probleme 404
spring.mvc.throw-exception-if-no-handler-found=true

# JWT Durer du token (24 heures)
jwt.expiration=86400000

# Pattern de log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Rotation des logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

# PROFIL ACTIF  Changer ici pour basculer DEV ? PROD
#spring.profiles.active=dev

# Upload avatars
fishcam.upload.avatar-dir=fishcam-data/avatars



# --- MINIO (S3 COMPATIBLE) ---
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:password123}
minio.bucket-name=${MINIO_BUCKET:fishcam-backups}

# --- CLOUDFLARE R2 (S3 COMPATIBLE) ---
cloudflare.r2.endpoint=${CLOUDFLARE_R2_ENDPOINT}
cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY}
cloudflare.r2.bucket-name=${CLOUDFLARE_R2_BUCKET_NAME}