# ???????????????????????????????????????????????????????????
# FISH-CAM ? Profil PRODUCTION
# ???????????????????????????????????????????????????????????
# Base de donn�es PROD
spring.datasource.url=jdbc:postgresql://localhost:5432/fishcam_db
spring.datasource.username=fishcam_user
spring.datasource.password=UnMotDePasseTresFort2026!
# IMPORTANT : update = ne modifie que ce qui a chang� (ne supprime RIEN)
spring.jpa.hibernate.ddl-auto=update
# PAS de SQL dans les logs en prod (performance)
spring.jpa.show-sql=false
logging.level.com.fishcam=INFO
logging.level.org.hibernate.SQL=WARN
# Cl� JWT PRODUCTION (DIFF�RENTE de dev !)
jwt.secret=UHJvZHVjdGlvblN1cGVyU2VjcmV0S2V5RmlzaENhbTIwMjZDaGFuZ2VNb2k=
# Logs dans un fichier
logging.file.name=/opt/fishcam/logs/application.log
# Rapport journalier ? TOUS LES JOURS � 19H
rapport.cron.expression=0 0 19 * * *
rapport.rattrapage.enabled=true
# Stockage avatars PROD
fishcam.upload.avatar-dir=/opt/fishcam/data/avatars