# FISH-CAM ? Profil D�VELOPPEMENT

# Base de donnees DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/fishcam_db_dev
spring.datasource.username=fishcam_user
spring.datasource.password=fishcam2025

# Recreer la base a chaque demarrage (JAMAIS en prod !)
spring.jpa.hibernate.ddl-auto=update

# Afficher les requetes SQL (debug)
spring.jpa.show-sql=true
logging.level.com.fishcam=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cle JWT de test (pas grave si elle est visible)
jwt.secret=ZmlzaGNhbXN1cGVyc2VjcmV0a2V5MjAyNWNoYW5nZW1laW5wcm9kdWN0assvW9uMTIzNDU2Nzg=
# Logs dans la console (pas de fichier en dev)
# logging.file.name=

# Rapport journalier ? TOUTES LES MINUTES pour tester
rapport.cron.expression=0 * * * * *
rapport.rattrapage.enabled=true

# Stockage avatars DEV
fishcam.upload.avatar-dir=fishcam-data-dev/avatars





# Indique � Spring Boot d'ex�cuter data.sql apr�s la cr�ation des tables
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true