# ////////////////////////////////////////
# FISH-CAM  Configuration commune
# ////////////////////////////////////////
spring.application.name=FishCam
spring.config.import=optional:file:.env

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA commun
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Serveur
server.port=8080
# Format dates (Cameroun)
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=Africa/Douala

# Upload fichiers (avatars, futurs PDF)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

# Resoud le probleme 404
spring.mvc.throw-exception-if-no-handler-found=true

# JWT Durer du token (24 heures)
jwt.expiration=86400000

# Pattern de log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Rotation des logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

# PROFIL ACTIF  Changer ici pour basculer DEV ? PROD
#spring.profiles.active=dev

# Upload avatars
fishcam.upload.avatar-dir=fishcam-data/avatars



# --- MINIO (S3 COMPATIBLE) ---
minio.endpoint=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=fishcam-backups

# --- CLOUDFLARE R2 (S3 COMPATIBLE) ---
cloudflare.r2.endpoint=https://<ACCOUNT_ID>.r2.cloudflarestorage.com
cloudflare.r2.access-key=ton_access_key
cloudflare.r2.secret-key=ton_secret_key
cloudflare.r2.bucket-name=fishcam-backups