#!/bin/bash
# Script de suppression des fichiers Dette - FishCam

echo "════════════════════════════════════════════════════════"
echo "🗑️  SUPPRESSION MODULE DETTE"
echo "════════════════════════════════════════════════════════"

# Chemin de base du projet (à adapter selon ton projet)
PROJECT_ROOT="src/main/java/com/fishcam"

echo ""
echo "📁 Suppression des ENTITÉS..."
rm -f "${PROJECT_ROOT}/domain/dette/Dette.java"
echo "   ❌ Dette.java"
rm -f "${PROJECT_ROOT}/domain/dette/StatutDette.java"
echo "   ❌ StatutDette.java"
rm -f "${PROJECT_ROOT}/domain/dette/TransactionDette.java"
echo "   ❌ TransactionDette.java"

echo ""
echo "📁 Suppression des REPOSITORIES..."
rm -f "${PROJECT_ROOT}/domain/dette/DetteRepository.java"
echo "   ❌ DetteRepository.java"
rm -f "${PROJECT_ROOT}/domain/dette/TransactionDetteRepository.java"
echo "   ❌ TransactionDetteRepository.java"

echo ""
echo "📁 Suppression du DOSSIER dette dans domain..."
rmdir "${PROJECT_ROOT}/domain/dette" 2>/dev/null && echo "   ✅ Dossier domain/dette supprimé" || echo "   ⚠️  Dossier non vide ou inexistant"

echo ""
echo "📁 Suppression des SERVICES..."
rm -f "${PROJECT_ROOT}/application/dette/DetteService.java"
echo "   ❌ DetteService.java"
rm -f "${PROJECT_ROOT}/application/dette/PayerDetteAvecEpargneUseCase.java"
echo "   ❌ PayerDetteAvecEpargneUseCase.java"
rmdir "${PROJECT_ROOT}/application/dette" 2>/dev/null && echo "   ✅ Dossier application/dette supprimé" || echo "   ⚠️  Dossier non vide"

echo ""
echo "📁 Suppression des REQUEST DTOs..."
rm -f "${PROJECT_ROOT}/adapter/web/dto/request/CreateDetteRequest.java"
echo "   ❌ CreateDetteRequest.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/request/RemboursementRequest.java"
echo "   ❌ RemboursementRequest.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/request/PayerDetteAvecEpargneRequest.java"
echo "   ❌ PayerDetteAvecEpargneRequest.java"

echo ""
echo "📁 Suppression des RESPONSE DTOs..."
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/DetteResponse.java"
echo "   ❌ DetteResponse.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/DetteDetailResponse.java"
echo "   ❌ DetteDetailResponse.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/TransactionDetteResponse.java"
echo "   ❌ TransactionDetteResponse.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/ClientDettesResponse.java"
echo "   ❌ ClientDettesResponse.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/PayerDetteAvecEpargneResponse.java"
echo "   ❌ PayerDetteAvecEpargneResponse.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/TopDebiteurResponse.java"
echo "   ❌ TopDebiteurResponse.java"
rm -f "${PROJECT_ROOT}/adapter/web/dto/response/StatistiquesDetteResponse.java"
echo "   ❌ StatistiquesDetteResponse.java"

echo ""
echo "📁 Suppression des CONTROLLERS..."
rm -f "${PROJECT_ROOT}/adapter/web/controller/DetteController.java"
echo "   ❌ DetteController.java"
rm -f "${PROJECT_ROOT}/adapter/web/controller/PayerDetteAvecEpargneController.java"
echo "   ❌ PayerDetteAvecEpargneController.java"

echo ""
echo "📁 Suppression des MAPPERS..."
rm -f "${PROJECT_ROOT}/adapter/web/mapper/DetteMapper.java"
echo "   ❌ DetteMapper.java"
rm -f "${PROJECT_ROOT}/adapter/web/mapper/TransactionDetteMapper.java"
echo "   ❌ TransactionDetteMapper.java"

echo ""
echo "════════════════════════════════════════════════════════"
echo "✅ SUPPRESSION TERMINÉE !"
echo "════════════════════════════════════════════════════════"
echo ""
echo "⚠️  PROCHAINES ÉTAPES :"
echo "1. Supprimer les imports Dette dans ClientService.java"
echo "2. Supprimer les imports Dette dans NotificationService.java"
echo "3. Supprimer la méthode createAlerteDette() dans NotificationService"
echo "4. Recompiler le projet : ./mvnw clean compile"
echo ""